CREATE TABLE ticket_id_sequence (
    next_val BIGINT NOT NULL
);

INSERT INTO ticket_id_sequence (next_val) VALUES (1004);

CREATE TABLE ticket (
    id VARCHAR(32) PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    description CLOB NOT NULL,
    status VARCHAR(20) NOT NULL,
    priority VARCHAR(10) NOT NULL,
    assignee VARCHAR(120),
    category VARCHAR(80),
    resolution_notes CLOB,
    knowledge_state VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    knowledge_version BIGINT NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_ticket_status ON ticket (status);
CREATE INDEX idx_ticket_priority ON ticket (priority);
CREATE INDEX idx_ticket_updated_at ON ticket (updated_at);

CREATE TABLE ticket_comment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id VARCHAR(32) NOT NULL,
    body CLOB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_comment_ticket FOREIGN KEY (ticket_id) REFERENCES ticket (id) ON DELETE CASCADE
);

CREATE INDEX idx_ticket_comment_ticket_created ON ticket_comment (ticket_id, created_at, id);

CREATE TABLE ticket_knowledge (
    id VARCHAR(36) NOT NULL PRIMARY KEY,
    ticket_id VARCHAR(32) NOT NULL,
    source_type VARCHAR(24) NOT NULL,
    source_id VARCHAR(64) NOT NULL,
    chunk_index INTEGER NOT NULL,
    content CLOB NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    ticket_version BIGINT NOT NULL,
    status VARCHAR(20),
    priority VARCHAR(10),
    assignee VARCHAR(120),
    category VARCHAR(80),
    embedding CLOB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_knowledge_ticket FOREIGN KEY (ticket_id) REFERENCES ticket (id) ON DELETE CASCADE,
    CONSTRAINT uq_knowledge_chunk UNIQUE (ticket_id, source_type, source_id, chunk_index)
);

CREATE INDEX idx_ticket_knowledge_ticket ON ticket_knowledge (ticket_id);
